{% set name = "ply" %}
{% set version = "3.11" %}
{% set sha256 = "00c7c1aaa88358b9c765b6d3000c6eec0ba42abca5351b095321aef446081da3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ply.lex
    - ply.yacc

about:
  home: http://www.dabeaz.com/ply/index.html
  license: BSD 3-clause
  license_family: BSD
  license_file: README.md
  summary: 'Python Lex-Yacc'
  description: |
    PLY is a 100% Python implementation of the common parsing tools lex and
    yacc.
  doc_url: http://www.dabeaz.com/ply/index.html
  dev_url: https://github.com/dabeaz/ply

extra:
  recipe-maintainers:
    - scopatz
    - synapticarbors
