travis:
  secure:
    BINSTAR_TOKEN: 0fsNAgm4rb/RH4tl2EOWuSEKdrV7HbUSC3zG+UxA+z0o3iHmV3ESg8/lTtOozpTD1Jrlr0Qv/ESNVOlggyyurPDiTPX6FsrUdNp7r0+5eA2OzF7nS7WEAtsxufIi83S7qeSiXBQ09mR+MecIqxhC3rbZw50qnxl2ZuWYXLFCJDThBMjK2B9ltnW5ugeku6x6OXZRhRNlwe8vcT+MJuDRqXFsxsNDczi38Y6u3Ei1ZINlGhSJTNMk0/bw52/YoxlDjGNM8QuIBFHd7eyuycu/ZjNKY9vTd3DoXveYyZDPeLhc5KQTc+8l2KXtYDBgHCUCOz24tzC/4Cbgiu7lssy6l3Rr4F8sTxPOK4HBNFUwbtKlyLlE0pYJHGnrnyER7zVj+n6bdQgYaTLms2WuUMgt7RQp4S7tpKhRCpH8Fb8ycmyEN55xtRPKQGgT+Ybhr2/906y2uOhCpX/9pkC45nPPQiA3MSKb4mJHQStYE/fujKu+l3LcRAsiXye1+XnMLmQI1om/crqji3d+iIBnFbW1TtfIF7Rvq59CDCFx8eVNO6SmOB66FCL0nPvyCbWuv8HZIy9492IcaXPJ3tWxGtmYDdBlOAyZw542urlhFirrYzDbupnlw/KnUAaGA87jr+tTFzw8/HwX4bMLxGR5XAl+4VYwVV9CwDOZdrCvAvkk6tE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
