travis:
  secure:
    BINSTAR_TOKEN: Qw58EZJn5CTPgqbtPNg0rPtyaK3xF+3TuntbtLMThLaNLaAlm/4VVhRI7BSU2SKou0h4cCEPeNhyxjcMZxzZ5WR1vyTgcAz7ZCYmW7n00MPcyMkT4DOoVWrnPlezHQ8bwEoO7FrO7kU8S7U22EE6IKPkqnWZy/bF5D23hHBPmi6csWkJOtq6CcOM/FO8feS4DFsY0u0GRmnG5uLKBvjM7AAOGXrSVKbVvDvgfSRTLepoBrSd6aLcySF19knUIlmMBb0xIliEhkl9wNUBQ4aE+f5L5dhJsEaW8tWomXbK4rlS8txi5wh/mWVFYcvzcDMloUYy1P0rVh8X8KWZCf03gCF4sNJOAFnuZj52hFCtwMTGbUt6v3zN0Q5xexmMovFDVV5Utd0wUNJyO55lD0vDocxDPOu5wItRMEZnSvIbzg9ckTMg0vicmYiqTKnlBwGXc53f1dL0ZZqFV6vTGMFOOf0qOvsYdjUK/LZtEndVYvQVQz98yfAtd9cMbQFBnPDale+pGuKDaEgha2yG2npxTy5cpiIHCHnkccMgeblfXGb3HYBIZGD/zO34heXbqbSfCQ1AJB4g2gjtKnyolu13p8GXTmnR3waVvbxgyLFWSGTuv8Au+T0UpeLHmFdsfS09eK5Z9X9yiRAGmbXJBQ0qcLtSFxYtAiVmeaVraqvGxHA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
